### ISSUE TITLE
How to add editable dependencies ?

### ISSUE THREAD

**Issue by ticosax** [darvid/reqwire#5]
Hi,
I'm interested to add editable dependencies like this:
```
-e git+https://github.com/darvid/reqwire.git@5b455cdca4e919041dfdf448c329eb206329b5e3#egg=reqwire
```

Is there is a way to achieve this ?

**Comment by darvid** [comment]
Not currently, no; will look into adding support tonight.

**Comment by darvid** [comment]
Preliminary support for editable requirements has been added in 0.1.5, although it doesn't work with packages that use setuptools_scm (yet).

**Comment by darvid** [comment]
Please try out [0.1.6](https://github.com/darvid/reqwire/releases/tag/0.1.6), there should be full support for installing/adding editable projects now.

``reqwire add -e <path/url>``

For the sake of posterity, VCS URLs to projects that use setuptools_scm cannot currently be used with pip-tools, due to nvie/pip-tools#369. I fixed it downstream here in reqwire, but ideally, [this pull request](https://github.com/nvie/pip-tools/pull/385) will get merged upstream soon.

**Comment by ticosax** [comment]
thanks a lot @darvid !
